### ISSUE TITLE
training error using train.sh 

### ISSUE THREAD

**Issue by kaishijeng** [terrychenism/mx-rfcn#1]
Terry,

I have created all required directories and data based your README.
How ever I encounters the following error when running train.sh. Do you know what can be wrong?

INFO:root:############### TRAIN FASTER-RCNN WITH APPROXIMATE JOINT END2END ##################
          -----------------------------------------------------------------------------------
INFO:root:Namespace(bn_mom=0.99, dataset_root='/home/fc/2TB/src/mx-rfcn/data', devkit_path='/home/fc/2TB/src/mx-rfcn/data/VOCdevkit', factor_step=50000, frequent=20, gpu_ids='0', image_set='trainval', kv_store='device', load_epoch=0, lr=0.001, mom=0.9, monitor=False, need_mean=False, no_flip=False, no_shuffle=False, num_classes=21, num_epoch=10, outdata_path='/home/fc/2TB/src/mx-rfcn/data', prefix='/home/fc/2TB/src/mx-rfcn/model/faster-resnext-101', pretrained='/home/fc/2TB/src/mx-rfcn/model/resnext-101', resume=False, root_path='/home/fc/2TB/src/mx-rfcn/data', test_image_set='test', train_rfcn=True, wd=0.0005, year='2007')

          -----------------------------------------------------------------------------------
INFO:root:########## TRAIN R-FCN WITH APPROXIMATE JOINT END2END #############
voc_2007_trainval gt roidb loaded from /home/fc/2TB/src/mx-rfcn/data/cache/voc_2007_trainval_gt_roidb.pkl
append flipped images to roidb
prepare roidb
[20:43:21] src/engine/engine.cc:36: MXNet start using engine: NaiveEngine
/home/fc/2TB/src/mx-rfcn/model/resnext-101-0000.params
Traceback (most recent call last):
  File "train_end2end_resnext.py", line 239, in <module>
    main()
  File "train_end2end_resnext.py", line 145, in main
    args_params, auxs_params, _ = load_param(args.pretrained, args.load_epoch, convert=True)
  File "/home/fc/2TB/src/mx-rfcn/utils/load_model.py", line 112, in load_param
    repeat = arg_params['rfcn_bbox_bias'].shape[0] / means.shape[1]
KeyError: 'rfcn_bbox_bias'
[20:43:21] src/engine/naive_engine.cc:28: Engine shutdown

**Comment by terrychenism** [comment]
fixed.  https://github.com/terrychenism/mx-rfcn/commit/a4d39f32830f88449fb6081302898be691b9cf9e

**Comment by kaishijeng** [comment]
Terry

   Thanks for the quick fix. Now training is running OK.
I encounter an issue of demo.py with your pretrained final-0000.params. Any
idea?

python demo.py --prefix final --epoch 0 --image ~/Pictures/pedestrian4.jpg
--gpu 0

Traceback (most recent call last):
  File "demo.py", line 88, in <module>
    demo_net(detector, args.image)
  File "demo.py", line 51, in demo_net
    scores, boxes = detector.im_detect(im_array, im_info)
  File "/home/fc/2TB/src/mx-rfcn/rcnn/detector.py", line 56, in im_detect
    grad_req='null', aux_states=self.aux_params)
  File
"/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py",
line 796, in bind
    args_handle, args = self._get_ndarray_inputs('args', args,
listed_arguments, False)
  File
"/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py",
line 638, in _get_ndarray_inputs
    raise ValueError('Must specify all the arguments in %s' % arg_key)
ValueError: Must specify all the arguments in args

**Comment by terrychenism** [comment]
sorry about the confusion, the pretrain model is faster-rcnn not r-fcn, I will update recently.

**Comment by kaishijeng** [comment]
Terry

  Thanks for clarification. Do you have a pretrained rfcn model available
for testing?

**Comment by kaishijeng** [comment]
Terry

I have finished training of the first epoch and use it for demo.py.
Unfortunately, there is still an error with my own training params.
Do you know why?

python demo.py --prefix model/resnext-101 --epoch 0 --image
~/Pictures/pedestrian4.jpg --gpu 0
[23:56:41] /home/fc/2TB/src/mxnet/dmlc-core/include/dmlc/logging.h:235:
[23:56:41] src/operator/./reshape-inl.h:288: Check failed: (new_size %
proposed_dim) == (0) Illegal dim setting, can't be divided.
infer_shape error. Arguments:
  data: (1L, 3L, 600L, 954L)
  im_info: (1L, 3L)
Traceback (most recent call last):
  File "demo.py", line 88, in <module>
    demo_net(detector, args.image)
  File "demo.py", line 51, in demo_net
    scores, boxes = detector.im_detect(im_array, im_info)
  File "/home/fc/2TB/src/mx-rfcn/rcnn/detector.py", line 42, in im_detect
    self.symbol.infer_shape(data=self.arg_params['data'].shape,
im_info=self.arg_params['im_info'].shape)
  File
"/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py",
line 459, in infer_shape
    return self._infer_shape_impl(False, *args, **kwargs)
  File
"/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py",
line 526, in _infer_shape_impl
    ctypes.byref(complete)))
  File
"/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.py",
line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: InferShape Error in cls_score_reshape: [23:56:41]
src/operator/./reshape-inl.h:288: Check failed: (new_size % proposed_dim)
== (0) Illegal dim setting, can't be divided.

**Comment by terrychenism** [comment]
also quick fix https://github.com/terrychenism/mx-rfcn/commit/e3907bfc006beb930d4ae6ff11111b8e31614454

I will refactor some codes these days.

**Comment by kaishijeng** [comment]
With e3907bf, somehow my own trained model doesn't have."rfcn_bbox_bias".
See below. I also dump all keywords in arg_params.

python demo.py --prefix model/resnext-101 --epoch 0 --image
~/Pictures/peds-008.png --gpu 0

  File "demo.py", line 87, in <module>
    detector = get_net(args.prefix, args.epoch, ctx)
  File "demo.py", line 20, in get_net
    args, auxs, num_class = load_param_rfcn(prefix, epoch, convert=True,
ctx=ctx)
  File "/home/fc/2TB/src/mx-rfcn/utils/load_model.py", line 112, in
load_param_rfcn
    repeat = arg_params['rfcn_bbox_bias'].shape[0] / means.shape[1]
KeyError: 'rfcn_bbox_bias'

ketwords in aug_params:

['stage3_unit2_bn3_beta', 'stage2_unit2_bn1_beta',
'stage3_unit11_bn1_gamma', 'stage3_unit14_conv3_weight',
'stage2_unit1_sc_weight', 'stage3_unit5_bn3_gamma',
'stage3_unit3_conv1_weight', 'stage2_unit1_bn3_gamma',
'stage3_unit15_conv3_weight', 'stage3_unit5_bn2_beta',
'stage1_unit3_bn2_gamma', 'stage3_unit23_conv1_weight',
'stage4_unit1_conv3_weight', 'stage1_unit3_bn3_gamma',
'stage3_unit12_bn3_beta', 'stage2_unit2_bn3_beta',
'stage3_unit17_conv3_weight', 'stage3_unit16_conv3_weight', 'conv0_weight',
'stage2_unit2_conv1_weight', 'stage3_unit20_bn1_beta',
'stage3_unit11_bn3_beta', 'stage3_unit2_conv2_weight',
'stage1_unit2_conv1_weight', 'stage3_unit20_conv3_weight',
'stage4_unit2_bn3_beta', 'stage3_unit14_conv1_weight',
'stage3_unit18_conv2_weight', 'stage3_unit18_bn3_gamma',
'stage3_unit23_bn2_beta', 'stage2_unit1_conv3_weight',
'stage3_unit2_bn2_gamma', 'stage3_unit15_bn3_beta',
'stage3_unit16_bn1_gamma', 'stage1_unit1_conv1_weight',
'stage3_unit9_conv2_weight', 'stage3_unit13_conv1_weight',
'stage4_unit1_sc_bn_gamma', 'stage4_unit1_bn3_beta',
'stage4_unit3_conv3_weight', 'stage3_unit18_bn1_gamma',
'stage4_unit3_bn1_gamma', 'stage2_unit1_bn2_beta',
'stage3_unit17_bn2_gamma', 'stage3_unit8_bn1_beta',
'stage3_unit11_conv1_weight', 'stage3_unit1_sc_weight',
'stage3_unit23_bn1_gamma', 'stage3_unit22_bn2_beta',
'stage3_unit19_conv2_weight', 'stage4_unit2_bn1_gamma',
'stage3_unit11_conv3_weight', 'stage3_unit21_conv3_weight',
'stage2_unit2_conv2_weight', 'stage3_unit7_conv1_weight',
'stage3_unit21_bn2_gamma', 'stage3_unit22_bn2_gamma',
'stage3_unit22_bn3_gamma', 'stage3_unit20_bn2_gamma',
'stage1_unit2_bn2_beta', 'stage1_unit3_bn1_beta',
'stage3_unit10_conv2_weight', 'stage3_unit12_conv1_weight',
'stage3_unit2_bn1_beta', 'stage3_unit10_bn2_beta',
'stage2_unit3_bn3_gamma', 'stage3_unit8_bn3_beta',
'stage3_unit16_bn2_gamma', 'stage3_unit14_bn3_gamma',
'stage4_unit2_conv3_weight', 'stage3_unit9_bn3_gamma',
'stage2_unit3_bn3_beta', 'stage2_unit2_conv3_weight',
'stage3_unit7_bn1_beta', 'stage3_unit21_bn1_beta', 'stage3_unit1_bn2_beta',
'stage3_unit16_conv2_weight', 'bn0_beta', 'stage3_unit12_bn1_gamma',
'stage2_unit4_bn1_gamma', 'stage3_unit4_conv1_weight',
'stage3_unit18_bn2_gamma', 'stage2_unit2_bn2_gamma',
'stage3_unit15_conv2_weight', 'stage3_unit14_conv2_weight',
'stage2_unit1_bn1_gamma', 'stage2_unit4_bn3_beta', 'bn0_gamma',
'stage3_unit15_bn1_gamma', 'stage1_unit1_bn2_beta',
'stage1_unit1_sc_bn_gamma', 'stage3_unit8_bn2_beta',
'stage2_unit4_bn1_beta', 'stage3_unit15_bn1_beta',
'stage4_unit2_conv2_weight', 'stage3_unit4_bn2_gamma',
'stage3_unit9_bn3_beta', 'stage3_unit1_conv3_weight',
'stage3_unit1_bn1_beta', 'stage3_unit22_conv3_weight',
'stage1_unit3_conv2_weight', 'stage4_unit1_bn1_gamma',
'stage3_unit2_conv3_weight', 'stage2_unit1_conv2_weight',
'stage4_unit1_conv1_weight', 'stage3_unit17_conv2_weight',
'stage1_unit2_bn3_beta', 'stage3_unit21_conv2_weight',
'stage4_unit3_conv1_weight', 'stage2_unit3_bn2_beta',
'stage3_unit18_conv3_weight', 'stage3_unit13_bn3_beta',
'stage3_unit19_conv1_weight', 'stage3_unit11_conv2_weight',
'stage3_unit6_bn2_gamma', 'stage3_unit5_bn2_gamma',
'stage3_unit9_conv1_weight', 'stage3_unit12_bn1_beta',
'stage2_unit4_bn2_beta', 'stage1_unit3_conv3_weight',
'stage3_unit13_bn2_gamma', 'stage3_unit22_conv1_weight',
'stage3_unit20_bn2_beta', 'stage2_unit2_bn3_gamma', 'fc1_weight',
'stage3_unit8_conv2_weight', 'stage1_unit3_bn2_beta',
'stage3_unit20_bn3_beta', 'stage3_unit9_conv3_weight',
'stage3_unit15_bn3_gamma', 'stage3_unit1_bn1_gamma',
'stage3_unit21_bn3_beta', 'stage1_unit1_conv2_weight',
'stage3_unit23_conv2_weight', 'stage3_unit3_bn3_beta',
'stage3_unit16_bn1_beta', 'stage3_unit6_conv1_weight',
'stage3_unit17_bn2_beta', 'stage3_unit20_bn3_gamma',
'stage1_unit2_bn2_gamma', 'stage4_unit1_bn3_gamma',
'stage3_unit14_bn2_beta', 'stage3_unit6_bn1_beta',
'stage4_unit1_sc_weight', 'stage3_unit1_bn3_beta',
'stage3_unit14_bn1_gamma', 'stage3_unit19_bn1_gamma',
'stage3_unit21_conv1_weight', 'stage3_unit6_conv2_weight',
'stage3_unit23_bn1_beta', 'stage4_unit3_conv2_weight',
'stage4_unit1_bn2_beta', 'stage3_unit17_bn3_beta',
'stage3_unit23_conv3_weight', 'stage3_unit7_bn2_beta',
'stage3_unit4_bn2_beta', 'stage3_unit7_bn2_gamma',
'stage3_unit18_bn2_beta', 'stage3_unit7_bn3_gamma',
'stage2_unit3_bn2_gamma', 'stage3_unit9_bn1_beta', 'stage1_unit2_bn1_beta',
'stage4_unit3_bn2_beta', 'stage3_unit8_conv3_weight',
'stage3_unit1_bn3_gamma', 'stage3_unit6_bn3_beta',
'stage3_unit5_bn1_gamma', 'stage2_unit4_conv1_weight',
'stage3_unit11_bn2_beta', 'stage1_unit1_bn3_gamma',
'stage3_unit21_bn2_beta', 'bn_data_gamma', 'stage2_unit2_bn2_beta',
'stage3_unit22_bn3_beta', 'stage3_unit13_bn1_beta',
'stage4_unit2_conv1_weight', 'stage1_unit3_bn1_gamma',
'stage3_unit10_conv1_weight', 'stage3_unit23_bn3_gamma',
'stage3_unit11_bn1_beta', 'stage1_unit3_conv1_weight',
'stage3_unit3_bn2_gamma', 'stage3_unit7_conv3_weight',
'stage3_unit1_conv2_weight', 'stage3_unit12_bn2_beta',
'stage3_unit13_conv3_weight', 'stage1_unit2_bn3_gamma',
'stage3_unit17_conv1_weight', 'stage4_unit1_conv2_weight',
'stage3_unit3_conv2_weight', 'stage4_unit1_bn2_gamma',
'stage1_unit1_sc_weight', 'stage3_unit6_bn2_beta',
'stage3_unit21_bn3_gamma', 'stage1_unit1_conv3_weight',
'stage4_unit1_bn1_beta', 'stage3_unit1_conv1_weight',
'stage3_unit19_bn2_beta', 'stage1_unit1_bn1_beta', 'stage3_unit3_bn2_beta',
'stage3_unit10_bn1_gamma', 'stage3_unit14_bn2_gamma',
'stage3_unit2_bn2_beta', 'stage3_unit3_bn3_gamma', 'stage4_unit3_bn3_beta',
'stage3_unit20_bn1_gamma', 'stage3_unit12_conv2_weight',
'stage3_unit1_bn2_gamma', 'stage3_unit10_bn3_gamma',
'stage3_unit2_bn3_gamma', 'stage3_unit4_bn3_gamma',
'stage4_unit3_bn3_gamma', 'stage3_unit7_bn1_gamma',
'stage3_unit15_bn2_beta', 'stage2_unit3_bn1_gamma',
'stage3_unit12_conv3_weight', 'stage3_unit18_bn1_beta',
'stage1_unit1_sc_bn_beta', 'stage3_unit15_bn2_gamma',
'stage2_unit3_bn1_beta', 'stage3_unit8_bn3_gamma',
'stage2_unit1_sc_bn_gamma', 'stage3_unit4_bn1_gamma',
'stage3_unit16_bn2_beta', 'stage3_unit6_conv3_weight',
'stage3_unit19_bn1_beta', 'stage4_unit2_bn2_beta',
'stage3_unit15_conv1_weight', 'stage3_unit6_bn3_gamma',
'stage4_unit1_sc_bn_beta', 'stage3_unit13_bn1_gamma', 'bn_data_beta',
'stage3_unit8_bn1_gamma', 'stage2_unit1_bn3_beta',
'stage4_unit3_bn2_gamma', 'stage3_unit5_bn3_beta',
'stage2_unit1_sc_bn_beta', 'stage3_unit7_bn3_beta',
'stage3_unit4_bn1_beta', 'stage3_unit22_conv2_weight',
'stage3_unit17_bn3_gamma', 'stage3_unit13_bn2_beta',
'stage3_unit18_bn3_beta', 'stage2_unit4_conv2_weight',
'stage3_unit2_bn1_gamma', 'stage3_unit11_bn3_gamma',
'stage3_unit9_bn2_gamma', 'stage3_unit10_bn3_beta',
'stage2_unit1_bn2_gamma', 'stage3_unit14_bn1_beta',
'stage1_unit1_bn3_beta', 'stage1_unit1_bn2_gamma',
'stage3_unit19_bn3_gamma', 'stage3_unit10_conv3_weight',
'stage3_unit19_conv3_weight', 'stage2_unit1_bn1_beta',
'stage3_unit9_bn1_gamma', 'stage3_unit5_conv2_weight',
'stage3_unit5_conv1_weight', 'stage3_unit20_conv2_weight',
'stage3_unit20_conv1_weight', 'stage4_unit2_bn2_gamma',
'stage3_unit18_conv1_weight', 'stage3_unit8_conv1_weight',
'stage3_unit4_conv2_weight', 'stage3_unit2_conv1_weight',
'stage3_unit19_bn2_gamma', 'stage3_unit16_bn3_gamma',
'stage3_unit16_bn3_beta', 'stage4_unit3_bn1_beta',
'stage3_unit1_sc_bn_beta', 'stage2_unit1_conv1_weight',
'stage3_unit21_bn1_gamma', 'stage3_unit13_bn3_gamma',
'stage3_unit12_bn3_gamma', 'stage4_unit2_bn1_beta',
'stage3_unit5_bn1_beta', 'stage3_unit13_conv2_weight',
'stage3_unit3_bn1_beta', 'stage3_unit10_bn1_beta',
'stage3_unit23_bn2_gamma', 'stage3_unit16_conv1_weight',
'stage3_unit22_bn1_beta', 'stage4_unit2_bn3_gamma',
'stage2_unit2_bn1_gamma', 'stage2_unit3_conv3_weight',
'stage3_unit17_bn1_beta', 'stage1_unit2_conv3_weight',
'stage3_unit19_bn3_beta', 'stage3_unit1_sc_bn_gamma',
'stage3_unit14_bn3_beta', 'stage3_unit10_bn2_gamma',
'stage3_unit6_bn1_gamma', 'stage3_unit11_bn2_gamma',
'stage1_unit2_bn1_gamma', 'stage3_unit3_conv3_weight',
'stage1_unit3_bn3_beta', 'stage2_unit4_bn2_gamma',
'stage2_unit4_conv3_weight', 'stage3_unit17_bn1_gamma',
'stage3_unit4_bn3_beta', 'stage2_unit3_conv1_weight',
'stage1_unit2_conv2_weight', 'stage3_unit3_bn1_gamma',
'stage1_unit1_bn1_gamma', 'stage3_unit23_bn3_beta',
'stage3_unit7_conv2_weight', 'stage3_unit22_bn1_gamma',
'stage3_unit12_bn2_gamma', 'stage3_unit8_bn2_gamma',
'stage3_unit4_conv3_weight', 'stage2_unit3_conv2_weight',
'stage3_unit9_bn2_beta', 'stage2_unit4_bn3_gamma', 'fc1_bias',
'stage3_unit5_conv3_weight']

**Comment by terrychenism** [comment]
You are using the resnext-101 model not r-fcn model .

**Comment by kaishijeng** [comment]
You are right. I made a mistake in the param filename.

Now it works and thanks
